version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
    groups:
      fluxzero-sdk:
        patterns: ["io.fluxzero:*"]
        update-types: [minor, patch]
      maven-non-major:
        patterns: ["*"]
        exclude-patterns: ["io.fluxzero:*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
    groups:
      npm-non-major:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
    groups:
      actions-non-major:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps
